version: '3.8'

services:
#  db:
#    image: mysql:8
#    container_name: my-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: test
#      MYSQL_USER: test
#      MYSQL_PASSWORD: test
#    ports:
#      - "13306:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 5s
#      retries: 10

  app:
    image: eclipse-temurin:17-jdk  # OpenJDK 17 런타임 이미지
    container_name: spring-app
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test
#      SPRING_DATASOURCE_USERNAME: test
#      SPRING_DATASOURCE_PASSWORD: test
    volumes:
      - ./app.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
    ports:
      - "8080:8080"